### ISSUE TITLE
set up staging site for netlify 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#106]
currently, the only option on the Netlify CMS is to "publish now." 
We need to be able to push new changes to the website first to staging, and then to production. Please set up a staging environment in netlify.

**Comment by LayaTaal** [comment]
It looks like we can utilize [Editorial Workflow](https://www.netlifycms.org/docs/configuration-options/#publish-mode) to help with this somewhat. Although it still doesn't allow for a full preview ability.
