### ISSUE TITLE
Fix issue with react-mailchimp-subscribe + captcha

### ISSUE THREAD

**Issue by judan** [texas-justice-initiative/website-nextjs#13]
This is a known issue: https://github.com/revolunet/react-mailchimp-subscribe/issues/13

To fix, we can disable "Captcha enabled" in Mailchimp and implement captcha ourselves.

**Comment by nholden** [comment]
We decided to rely on Mailchimp's captcha in https://github.com/texas-justice-initiative/website-nextjs/pull/129.
