### ISSUE TITLE
Fix gap in header navigation submenu

### ISSUE THREAD

**Issue by LayaTaal** [texas-justice-initiative/website-nextjs#131]
Fix an issue in the header nav that makes it difficult to move the mouse into submenus:

![Oct-21-2019 14-26-24](https://user-images.githubusercontent.com/22242017/67236424-de6e4980-f40e-11e9-868f-e3dc7351a93c.gif)

**Comment by judan** [comment]
Oh you already made an issue! I'll close my duplicate. Also, I think this is just a matter of moving the hover effect from the <a> to the containing <div>.  I'll take it.

**Comment by judan** [comment]
@LayaTaal I'm trying to reproduce this bug and have been unable to. Are you still seeing issues? Or maybe you checked in some styles related to this?
