### ISSUE TITLE
Change values for "Civilian Died"

### ISSUE THREAD

**Issue by LayaTaal** [texas-justice-initiative/website-nextjs#133]
Users found the labels of true/false confusing for "Civilian Died". Can we change these values from "true/false" to "death/injury" to match other charts and be more clear?

<img width="1025" alt="Screen Shot 2019-10-21 at 4 14 27 PM" src="https://user-images.githubusercontent.com/22242017/67243740-e1246b00-f41d-11e9-8598-986993ac1ef5.png">

**Comment by athpud** [comment]
I think the changes to be made are going to be in the following script, leaving this here mostly for myself to investigate later: https://github.com/texas-justice-initiative/data-processing/blob/master/data_cleaning/create_datasets_for_website.ipynb
