### ISSUE TITLE
Convert markdown to html

### ISSUE THREAD

**Issue by LayaTaal** [texas-justice-initiative/website-nextjs#148]
Currently the newsfeed is maintained in [Netlify CMS](https://texasjusticeinitiative.netlify.com/static/admin). The CMS stores posts in a markdown file which we then post to the homepage. At the moment markdown isn't being converted and comes through as plain text. We need to make sure to convert this.

<img width="1090" alt="Screen Shot 2019-10-30 at 10 48 00 AM" src="https://user-images.githubusercontent.com/22242017/67874491-fc206a80-fb02-11e9-8de5-cfc468114641.png">

**Comment by LayaTaal** [comment]
I have been looking into this today and wanted to add some more information:

It seems like there may be an issue with the plugin we are using to convert markdown ([frontmatter-markdown-loader](https://hmsk.github.io/frontmatter-markdown-loader/)) not being able to convert markdown from frontmatter fields into html. 

We may need to look into another loader.

**Comment by judan** [comment]
@LayaTaal Hrmmm, that plugin came straight from the docs, I believe.
