### ISSUE TITLE
Integrate incarceration map into new site

### ISSUE THREAD

**Issue by LayaTaal** [texas-justice-initiative/website-nextjs#149]
@jonathanpascoe has made a really great map of incarceration patterns at the county level in Texas. We would like to create a new page (for now) on the site to hold this map.

**Useful Links**
- [Project Repo](https://github.com/texas-justice-initiative/texas_incarceration_map) - The work behind this project
- [Live Map](http://tji-map-viewer.s3-website.us-east-2.amazonaws.com/) - Working version of this map

**Comment by EvaRuthM** [comment]
Tip from JP: “This is react and mapbox js. Integration can be as simple as a frame or embedding of react components.  Really depends on how the primary website devs want to go about it”
