### ISSUE TITLE
"thanks" for icons on about the data

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#152]
please add the appropriate "thanks" for icons used in the "about the data" page to our other "thanks"

**Comment by athpud** [comment]
@LayaTaal @jen-k @EvaRuthM Hi y'all, I've added a draft of the 'Thanks!' page on the WordPress site-- it's called "Thanks! -- Athula's Edits." In that draft, I've added the attributions for all the icons I've used in the data processing figures. Let me know if you need anything else from me to help integrate it into the Netlify site.

**Comment by EvaRuthM** [comment]
hi @athpud, thanks so much, this is fine with me. 
@LayaTaal, can you get this page on the redesigned site please?
