### ISSUE TITLE
Link to incarceration map

### ISSUE THREAD

**Issue by nholden** [texas-justice-initiative/website-nextjs#169]
In https://github.com/texas-justice-initiative/website-nextjs/pull/155, we added a new page, https://texasjusticeinitiative.netlify.com/map, that shows the awesome map by @jonathanpascoe. We still need to link to that page somewhere on the site.

**Comment by EvaRuthM** [comment]
Please link to the map thusly: 
- [ ] on the "Explore the Data" page, please add a button next to "Download" that says: "Map View" 
- [ ] on the "Publications" page, please add the following text: 

> **Map views of TJI's data (2019)**
> By Jonathan Pascoe
> Map views of TJI's data on officer-involved shootings and custodial deaths. 
> [TJI Maps](link)
