### ISSUE TITLE
send notification email when survey filled out

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#210]
Please have our system send an email to "info@texasjusticeinitiative.org" when someone fills out the Netlify survey upon downloading data.

**Comment by nholden** [comment]
From https://app.netlify.com/sites/texasjusticeinitiative/settings/forms, it looks like this is already wired up properly. Let me know if you aren't receiving emails that you're expecting and I can dig in deeper.

<img width="944" alt="Screen Shot 2020-01-20 at 1 41 13 PM" src="https://user-images.githubusercontent.com/7942714/72759437-9932f280-3b8a-11ea-8a86-56466e15ef7b.png">
