### ISSUE TITLE
move all pages to Netlify CMS 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#211]
(except for Explore) 

- [x] about TJI 
- [x] about the data 
- [x] related organizations
- [x] publications
- [x] thanks
- [x] donate
- [x] volunteer
- [x] contact
- [ ] last updated dates on data sets
- [x] COVID fatalities map

**Comment by nholden** [comment]
Most of this work is done, and we've been proactive about moving existing content to the CMS as it needs to be edited, so I'll close this out.
