### ISSUE TITLE
add Bergan back to about us

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#286]
I took Bergan off of the "volunteer" portion of the About Us page because she's technically not a volunteer. 

I'd like to add her back to the "who we are" section right under me. I almost have this capability in the CMS but can't add someone other than to the volunteers section....can someone give me a hand?

**Comment by nholden** [comment]
👋 Hi, @EvaRuthM! I just updated the CMS so that we can include multiple people under the "who we are" heading. Let me know if that works for you or if you were thinking of something else!
