### ISSUE TITLE
capture cloudinary analytics 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#309]
**PROBLEM:** we'd like to track the number of website visitors who watch the video embedded on the top of our "About Us" page 

- [ ] potential solution 1: research ways to connect our traffic via Cloudinary to Google Analytics and create fix that way; or 
- [ ] potential solution 2: customize the embed format of our video (use something other than an iframe)

**Comment by nholden** [comment]
It looks like we'll need a combination of potential solutions 1 and 2. We can [send events from the video player to Google Analytics](https://cloudinary.com/documentation/video_player_events_analytics#tracking_video_player_analytics), but we'll need to switch from the cloud-based player we're currently using to a [self-hosted player](https://cloudinary.com/documentation/video_player_how_to_embed#self_hosted_player). I can dig in a bit more this week!
