### ISSUE TITLE
workaround to automatically update Tableau

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#313]
**PROBLEM:** We use Tableau Public for our dashboards, but it will only stay automatically updated to data in Google Sheets if the Google Sheet is on an individual's drive and not a team drive. We currently address this by connecting Tableau Public to our data.world, but that is not ideal and is clunky and the connection breaks. 

**SOLUTION:** Ideal: clone the Google Sheet onto a personal drive sheet (and build it so that _it_ stays automatically updated when the original is updated)

**Comment by babyakja** [comment]
Fixing python package difference for pygsheets

**Comment by babyakja** [comment]
New notebook pulled to AWS that will write dataset directly to Google Drive. This file will automatically update Tableau Dashboard.
