### ISSUE TITLE
create review process for TJI content 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#385]
establish processes to peer-review all TJI content: 
- published reports 
- blog posts 
- data visualization tools 
- other types of analyses?

**Comment by hongsups** [comment]
Given the fact that most of our work products go into github, I think we can utilize github for our review tool. This way our reviews will be also public and we'll be even more transparent. If it's a software engineering task, it's going to be a very typical merge request code review process.

This could be debatable but I think even for the non-code materials (such as text report), everyone can just create a document using markdown (.md) or reStructuredText (.rst) then we can easily version control it here. (markdown is super easy to learn and there's nothing much to learn to begin with, rst has slightly more to learn but it's manageable). This way, everything will be in github. This could be a little bit challenging in the beginning but I find this pretty useful. An example that I participated in this year, which used github review process using RST is here: https://github.com/scipy-conference/scipy_proceedings/pull/550/files/3f0e3ac16656f4ef80436c6c7691ce005e17e4a4 (go to the bottom of the page and you'll find a rst file, and click load diff, then you'll see the conversation between authors and reviewers)

For jupyter notebooks, getting diff is a bit more challenging but there are open source tools, so we can simply use those.
