### ISSUE TITLE
Pull data fetch into an HOC; pass it into props

### ISSUE THREAD

**Issue by judan** [texas-justice-initiative/website-nextjs#40]
We need to find a way to to make the fetched data resuable on multiple pages so that we aren't duplicating code. Need to make it scalable for adding future datasets.

See this: https://github.com/zeit/next.js/issues/3489
And this: https://gist.github.com/dstreet/7642b229e33f3cfe137dd7f3bae7a37d

**Comment by nholden** [comment]
Since we've rearchitected our Explore the Data page, I'm not sure this is as immediately relevant, so I'll close it out.
