### ISSUE TITLE
add presentation video to website

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#405]
Please add [this video](https://drive.google.com/file/d/1aXvxJ8E4pP9uE4WU0dW3A4ncglxvZhCH/view?usp=sharing) to the website in two different places: 

- [x] embed it beneath the PDF (if possible?) on the [report page](https://texasjusticeinitiative.org/publications/officer-involved-shootings-in-texas) with a caption: "TJI presented our report and answered questions via Zoom on Aug. 26, 2020." 

- [x] provide a link (if possible?) to the video so that Eva Ruth can list and link it beneath the report on the "Publications" page

**Comment by nholden** [comment]
The video [is live on the website](https://texasjusticeinitiative.org/publications/officer-involved-shootings-in-texas)! Here's the link we can use on the publications page to go directly to that section of the page:

https://texasjusticeinitiative.org/publications/officer-involved-shootings-in-texas#virtual-report-presentation
