### ISSUE TITLE
change "download the data" survey back 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#422]
please restore our old survey questions that pop up when people click on "download the data" 
but remove the fundraising ask completely 

- is it possible to add a "can we contact you" section and collect their email addy?

**Comment by nholden** [comment]
> is it possible to add a "can we contact you" section and collect their email addy?

@EvaRuthM: with the old download the data modal, after the user completed the survey, we asked if they wanted to join the mailing list. The copy looked like this.

> Thank you for your interest in TJI! For regular updates on TJI’s data in use, our latest data offerings and the most recent revelations, sign up for our newsletter, a short read that hits inboxes monthly. We promise not to sell your email address.
>
> First name: [first name field]
> Last name: [last name field]
> Email: [email field]

What do you think about replacing that step with a "can we contact you" step and adding a checkbox to allow users to join the mailing list? I'm thinking that copy might look like this.

> Thank you for helping us better understand our users! If you'd like to allow us to contact you to learn more about how you use the data, please fill out the form below. We promise not to sell your email address.
>
> First name: [first name field]
> Last name: [last name field]
> Email: [email field]
> [checkbox (checked by default)] Sign me up for TJI‘s newsletter for regular updates on our latest data offerings and most recent revelations

**Comment by EvaRuthM** [comment]
sounds great, @nholden!
