### ISSUE TITLE
move all publication PDFs from Google Drive to netlify

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#425]
right now, two of our publications link to documents on our Google Drive. 
please move these onto Netlify so that people don't have to go through Drive. 
Publications include: 
 - [TJI Fact Sheet Shootings and Deaths (2018)](https://drive.google.com/file/d/1d2UBGXA_5YSv6TdcTZLrGe2X3zUBU3QR/view?usp=sharing)
- [Data Report for Life and Death in a Carceral State (2018)](https://drive.google.com/file/d/167qxHtgRhuCCcg2-VoYBMJ0buatf6krF/view)

**Comment by nholden** [comment]
I [just moved](https://github.com/texas-justice-initiative/website-nextjs/pull/427) all the PDFs on the publications page that were Google Drive links to Netlify!
