### ISSUE TITLE
Look into chart value discrepancies 

### ISSUE THREAD

**Issue by judan** [texas-justice-initiative/website-nextjs#48]
Look into why these two charts on the Civilians Shot set appear to be different from what's on the current site. 

<img width="728" alt="Screen Shot 2019-08-12 at 11 33 41 PM" src="https://user-images.githubusercontent.com/17421071/62915676-f82e4900-bd5a-11e9-8c9b-cdf394c327ce.png">

**Comment by LayaTaal** [comment]
No longer applies
