### ISSUE TITLE
TJI's stack 

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#497]
please "map out" our stack for the website and data processing

**Comment by nholden** [comment]
Here are tools we use for the website:

Application framework: [Next.js](https://nextjs.org/), which uses [React](https://reactjs.org/)
Application hosting: [Netlify](https://netlify.com)
Media hosting: [Cloudinary](https://cloudinary.com/)
Code hosting: [GitHub](https://github.com)
CMS: [Netlify CMS](https://netlifycms.org/)
Code style linting: [ESLint](https://eslint.org/), enforced by [GitHub Actions](https://github.com/features/actions)
Donation processing: [PayPal](https://paypal.com)
Charts: [Chart.js](https://www.chartjs.org/) and [Tableau](https://www.tableau.com/)
Maps: [Google Maps Platform](https://developers.google.com/maps/documentation/embed/get-started)
Forms: [Netlify Forms](https://www.netlify.com/products/forms/) and [Google Forms](https://www.google.com/forms/about/)
Newsletters: [Mailchimp](https://mailchimp.com)

**Comment by lukasbayern18** [comment]
General analysis: [Jupyter](https://jupyter.org)
Remote computing: [AWS](https://aws.amazon.com)
Data hosting: [data.world](https://data.world)
Python Packages: pandas, numpy, pygsheets, datadotworld
