### ISSUE TITLE
review "voice/tone" style guide

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#549]
Please review [these guidelines](https://docs.google.com/document/d/1_mx-tNvmOW7rkO2n1BFkZJi84FzMBxnNNQ7ykCMB6zw/edit) for TJI's writing voice and tone and add comments, make edits, etc.

**Comment by hongsups** [comment]
Really like the this style guide draft! Just left some comments. :)
