### ISSUE TITLE
submit photos and bios for website

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#551]
Please send @EvaRuthM your photo for the website along with a short description (2-3 words) for our [website](https://texasjusticeinitiative.org/about).

**Comment by shashaogork** [comment]
![39180A0E-9667-4E65-BE27-AF0FE9EE0690](https://user-images.githubusercontent.com/78510976/111923694-64f8e180-8a6e-11eb-8957-7138f1bd2782.jpeg)
bio- mentee
