### ISSUE TITLE
update Global Styles to match styleguide

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#602]
Please update the Global Styles in Netlify to mimic the **typography** as specified in the "[TJI Styleguide](https://docs.google.com/document/d/1n0QzA7jBB9lzAmrGDQvcIJYHZ5O1i_Zu0G1oHQW0cNc/edit#
)" 
- [ ] H1
- [ ] H2
- [ ] H3
- [ ] H4
- [ ] Body Copy
- [ ] Small Text

**Comment by nholden** [comment]
👋 @juliam16: I noticed that the headers in the style guide are bigger than the ones on currently on the website (e.g. `<h1>` is 32px on the website but 40px in the style guide). Do you think these headers should get bigger on the website, or should we make those smaller in the style guide?

**Comment by juliam16** [comment]
@nholden At the bottom of the home page 40px is being used for the "STATE OF THE DATA" title on the email sign up. Globally, the H1's on the top of each page should be 32px.
<img width="1116" alt="Screen Shot 2021-05-23 at 11 00 38 AM" src="https://user-images.githubusercontent.com/50604113/119267906-2a1e4180-bbb6-11eb-9172-bc4eab4dcaf5.png">
