### ISSUE TITLE
fork 1Password repo for free teams account

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website-nextjs#616]
We'd like to take advantage of 1Password's free services for open-source teams. Since we already have a 1Password Teams account, we just need to [pick this up at step 3](https://github.com/1Password/1password-teams-open-source). Please fork the 1Password repo and ping Eva Ruth with questions about the requirements or needed language.

**Comment by nholden** [comment]
I just opened https://github.com/1Password/1password-teams-open-source/pull/342 to apply for a free team account.

**Comment by nholden** [comment]
Just received an update from 1Password via email:

> Since you already have a subscription, and the non-profit promotion on your account, I need to check with a few other people here to see how we want to handle that. I'll get back to you as soon as I can!
