### ISSUE TITLE
Improve header nav on "tablet" viewports

### ISSUE THREAD

**Issue by nholden** [texas-justice-initiative/website-nextjs#624]
When my browser window is just wider than our mobile breakpoints so that the navigation links appear in the header instead of the menu button, our "donate" button is pushed onto the next line in an awkward way. Let's make that look nicer!

![Screen Shot 2021-06-13 at 11 07 38 AM](https://user-images.githubusercontent.com/7942714/121817770-2ec79a00-cc38-11eb-8425-e4314691db62.png)

**Comment by LayaTaal** [comment]
This has been completed as part of the blog updates.
