### ISSUE TITLE
Explore page mobile styles

### ISSUE THREAD

**Issue by judan** [texas-justice-initiative/website-nextjs#85]
This needs to be fixed. 
<img width="451" alt="Screen Shot 2019-09-15 at 9 25 40 AM" src="https://user-images.githubusercontent.com/17421071/64922988-f7923380-d79a-11e9-979c-b510b1f4deaa.png">

**Comment by judan** [comment]
Also, this happens whenever the Explore page filters and the Menu panel are open at the same time on mobile.
<img width="432" alt="Screen Shot 2019-09-15 at 9 32 46 AM" src="https://user-images.githubusercontent.com/17421071/64923068-fdd4df80-d79b-11e9-9dbb-17509806e625.png">

**Comment by LayaTaal** [comment]
Fixed in #90
