### ISSUE TITLE
Improve user experience on Explore page

### ISSUE THREAD

**Issue by LayaTaal** [texas-justice-initiative/website-nextjs#97]
The area above the charts has a lot of text, buttons, and other things going on which makes it difficult to read and a little messy overall.

We want to improve this to make the user experience better and so that new users can easily know how to use the page.

Some ideas are to create tooltips which display on hover, and perhaps also a small tutorial/demo for new users?

**Comment by EvaRuthM** [comment]
@LayaTaal - please change to this (let's delete all other text):
**on all versions**
> Latest data update: 09/04/2019. Raw data sets are available via data.world. 


**on mobile only**

> _Because the charts may become very large, this page is best viewed on a desktop or laptop screen._
